<?php

namespace Lendable\Interview\Tests;

use Lendable\Interview\FeeCalculatorController;
use Lendable\Interview\FeeCalculatorService;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

class FeeCalculatorControllerTest extends TestCase
{
    private FeeCalculatorController $controller;
    private FeeCalculatorService&MockObject $feeCalculatorService;

    public function setUp(): void
    {
        //TODO:: DI
        $this->feeCalculatorService = $this->createMock(FeeCalculatorService::class);
        $this->controller = new FeeCalculatorController($this->feeCalculatorService);
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function testExceptionThrownOnInvalidTerm(): void
    {
        $loanAmount = '19,250.00';
        $term = 'aswesese';
        $this->expectException(\Exception::class);
        $this->controller->getFeeForAmountAndTerm($loanAmount, $term);
    }

    public function testNoExceptionWithValidInputs(): void
    {
        $loanAmount = '19,250.00';
        $term = '24';
        $fakeFee = 38500;

        $this->feeCalculatorService->expects($this->once())->method('calculate')->willReturn($fakeFee);

        //TODO::Mock Service and return values
        $fee = $this->controller->getFeeForAmountAndTerm($loanAmount, $term);
        $this->assertEquals('385.00', $fee);
    }
}